/**
 * Island registry types.
 *
 * An IslandRegistry maps component names to dynamic import functions.
 * The registry is auto-generated by @emulsion/vite-plugin at build time
 * and lives at `islands/index.ts` in the user's application.
 */

import type { ComponentType } from "react";

/** Any React component that accepts arbitrary props. */
export type IslandComponent = ComponentType<Record<string, unknown>>;

/** A function that lazily imports an island module. */
export type IslandLoader = () => Promise<{ default: IslandComponent }>;

/** Maps island names to their lazy loaders. */
export type IslandRegistry = Record<string, IslandLoader>;

/**
 * Identity helper — satisfies TypeScript while keeping the registry
 * definition readable.
 *
 * Usage (in auto-generated islands/index.ts):
 *   export const registry = createRegistry({
 *     Counter: () => import("./Counter"),
 *   });
 */
export function createRegistry(registry: IslandRegistry): IslandRegistry {
  return registry;
}
