/**
 * Island registry for example-app.
 *
 * AUTO-GENERATED by @emulsion/vite-plugin — edit with care.
 * In production builds, this file is replaced by the virtual module.
 * In development, `virtual:emulsion-registry` serves a live-updated version.
 */

import { createRegistry } from "@emulsion/react";

export const registry = createRegistry({
  Counter: () => import("./Counter"),
  AddToCart: () => import("./AddToCart"),
  ReviewCarousel: () => import("./ReviewCarousel"),
});
